Fix ValueError when user has multiple profiles
niteoweb/pyramid_mixpanel pull request #48
Opened 2024-03-05 11:23 UTC by karantan

Return the first one and make a warning.

Ref: https://github.com/teamniteo/easyblognetworks/issues/3424

2024-03-05 11:24 UTC, zupo approved these changes

2024-03-05 11:25 UTC, zupo requested changes
wait

2024-03-05 11:27 UTC, zupo commented
It is hard to catch a log entry and do something more with it. Exceptions are much easier to work with, to cover various use cases.

So it's better if the code that use pyramid_mixpanel catches the ValueError exception and then does whatever it wants with it. 

If ValueError is not specific enough, let's add a more specific exception class to this package and then raise it.

2024-03-05 13:16 UTC, karantan commented
> It is hard to catch a log entry and do something more with it. Exceptions are much easier to work with, to cover various use cases.
> 
> So it's better if the code that use pyramid_mixpanel catches the ValueError exception and then does whatever it wants with it.
> 
> If ValueError is not specific enough, let's add a more specific exception class to this package and then raise it.

But we don't want to raise an error here. I guess ideally we would return an error and also value (users[0]) and leave it to the client to deal with it.

2024-03-05 16:25 UTC, zupo commented
How do you return an error and value?

2024-03-06 07:39 UTC, karantan commented
> How do you return an error and value?

I don't think that you can in Python. Custom error with users[0] makes sense. Should I make these changes?

2024-03-06 07:58 UTC, zupo commented
> > How do you return an error and value?
> 
> I don't think that you can in Python. Custom error with users[0] makes sense. Should I make these changes?

FWIW, I would return all users. Let the client code decide to use first, last, one at random, etc.

2024-03-06 08:15 UTC, karantan commented
> > > How do you return an error and value?
> > 
> > 
> > I don't think that you can in Python. Custom error with users[0] makes sense. Should I make these changes?
> 
> FWIW, I would save all users in the Exception. Let the client code decide to use first, last, one at random, etc.

ok

2024-03-07 12:19 UTC, zupo commented on pyramid_mixpanel/query.py
> +class MultipleProfilesFoundException(Exception):
Let's subclass from `ValueError` so that if any client code is catching `ValueError` the code keeps on working.

2024-03-07 12:20 UTC, zupo commented on setup.py
> +VERSION = "0.12.1"
```suggestion
VERSION = "0.13"
```

PATCH version bumps is only for (minor) bugfixes, this is closer to a new feature, so a MINOR version bump is more appropriate: https://semver.org/

2024-03-08 10:33 UTC, zupo approved these changes

2024-03-08 11:09 UTC, merged